import type {
  AgentNode,
  AgentEdge,
  Commit,
  Branch,
  ChatMessage,
  ToolExecution,
  AgentWorkflowDefinition,
  AgentWorkflowTemplate,
  AgentWorkflowComponent,
  AgentWorkflowOptions,
  AgentCausalMemoryNode,
  AgentCausalMemoryEdge,
  AgentPhase,
  OpenAICompatibleApiConfig,
} from './types'

const BASE_TIME = 1741132800000 // 2025-03-05 00:00:00 UTC

function createBaseWorkflowOptions(overrides: Partial<AgentWorkflowOptions> = {}): AgentWorkflowOptions {
  const base: AgentWorkflowOptions = {
    autonomousToolAgent: true,
    enableCausalMemory: false,
    includeProjectManifest: true,
    forceManifestFirst: false,
    includePreviousOutput: false,
    debugVerboseReport: true,
    causalMemoryTopK: 6,
    causalMemoryMaxChars: 1600,
    budget: {
      maxSteps: 6,
      maxRequests: 10,
      maxTotalTokens: 12000,
      maxParallelRequests: 1,
    },
    toolPermissions: {
      allowTelemetryRead: true,
      allowCodeSearch: true,
      allowCodeRead: true,
    },
    actionQuotas: {
      maxCodeReadActions: 6,
      maxCodeSearchActions: 6,
      maxTelemetrySliceActions: 6,
    },
  }

  return {
    ...base,
    budget: {
      ...base.budget,
      ...(overrides.budget ?? {}),
    },
    toolPermissions: {
      ...base.toolPermissions,
      ...(overrides.toolPermissions ?? {}),
    },
    actionQuotas: {
      ...base.actionQuotas,
      ...(overrides.actionQuotas ?? {}),
    },
    ...overrides,
  }
}

export const MOCK_API_CONFIG: OpenAICompatibleApiConfig = {
  enabled: false,
  baseUrl: 'https://api.openai.com/v1',
  apiKey: '',
  model: 'gpt-4o-mini',
  temperature: 0.2,
  maxTokens: 900,
}

function buildWorkflowComponents(_phaseBias: AgentPhase = 'discover'): AgentWorkflowComponent[] {
  return [
    {
      id: 'wf-orchestrator',
      type: 'run-orchestrator',
      name: 'RunAnalysis Agent Orchestrator',
      phase: 'discover',
      enabled: true,
      color: '#0070f3',
      description: '预算与阶段机控制（Baseline -> Loop -> Synthesis）',
      config: { blockedLimit: 4, reserveFinalSummaryRequest: true },
    },
    {
      id: 'wf-baseline',
      type: 'baseline-analyzer',
      name: 'Baseline Analyzer',
      phase: 'discover',
      enabled: true,
      color: '#22c55e',
      description: 'S1 基线分析，输出首轮结论与证据缺口',
      config: { modelStep: 'Baseline' },
    },
    {
      id: 'wf-manifest',
      type: 'manifest-loader',
      name: 'Manifest Loader',
      phase: 'discover',
      enabled: false,
      color: '#00d4ff',
      description: '可选预加载 manifest（默认由 Loop 中动作触发）',
      config: { maxCodeFilesInManifest: 120 },
    },
    {
      id: 'wf-planner',
      type: 'llm-planner',
      name: 'LLM Planner',
      phase: 'investigate',
      enabled: true,
      color: '#f59e0b',
      description: 'S2 循环规划动作（自治计划队列 + 阶段上下文）',
      config: { modelStep: 'Plan' },
    },
    {
      id: 'wf-governance',
      type: 'governance-gate',
      name: 'Deterministic Governance',
      phase: 'investigate',
      enabled: true,
      color: '#ec4899',
      description: '动作治理：去重、封禁、预算、finish 收敛控制',
      config: { repeatLimitSearch: 2, repeatLimitDefault: 3 },
    },
    {
      id: 'wf-tool',
      type: 'tool-executor',
      name: 'Tool Executor',
      phase: 'investigate',
      enabled: true,
      color: '#06b6d4',
      description: '执行工具动作并写入执行轨迹（manifest/search/read/telemetry）',
      config: {
        tools: ['get_project_manifest', 'query_telemetry_aggregate', 'read_telemetry_slice', 'search_code', 'read_code_file'],
      },
    },
    {
      id: 'wf-memory',
      type: 'causal-memory',
      name: 'Causal Memory Graph',
      phase: 'investigate',
      enabled: false,
      color: '#a855f7',
      description: '可选因果记忆检索增强（topK + chars）',
      config: { topK: 6, maxChars: 1600 },
    },
    {
      id: 'wf-evidence',
      type: 'evidence-hub',
      name: 'Evidence Hub',
      phase: 'investigate',
      enabled: true,
      color: '#14b8a6',
      description: '证据汇聚与裁剪，供最终综合阶段使用',
      config: { clipChars: 3200 },
    },
    {
      id: 'wf-summary',
      type: 'summary-synthesizer',
      name: 'Summary Synthesizer',
      phase: 'synthesize',
      enabled: true,
      color: '#22c55e',
      description: 'S5 综合输出最终结论（保留 Baseline + Evidence）',
      config: { modelStep: 'Summary' },
    },
    {
      id: 'wf-critique',
      type: 'critique-refiner',
      name: 'Critique / Refinement',
      phase: 'synthesize',
      enabled: false,
      color: '#f97316',
      description: '可选二轮批判与润色',
      config: { enableParallelCritique: true },
    },
  ]
}

export const MOCK_WORKFLOW_TEMPLATES: AgentWorkflowTemplate[] = [
  {
    id: 'tpl-runanalysis-compatible',
    name: 'RunAnalysis 平替模板',
    description: '与 Unity RunAnalysisAgentOrchestrator 同构的默认工作流',
    components: buildWorkflowComponents('discover'),
    options: createBaseWorkflowOptions(),
  },
  {
    id: 'tpl-runanalysis-deep',
    name: 'RunAnalysis 深挖模板',
    description: '提高预算并启用 Causal Memory，适用于复杂排障',
    components: buildWorkflowComponents('investigate'),
    options: createBaseWorkflowOptions({
      enableCausalMemory: true,
      budget: { maxSteps: 10, maxRequests: 14, maxTotalTokens: 24000, maxParallelRequests: 1 },
      actionQuotas: { maxCodeReadActions: 10, maxCodeSearchActions: 10, maxTelemetrySliceActions: 8 },
      causalMemoryTopK: 10,
      causalMemoryMaxChars: 2400,
    }),
  },
  {
    id: 'tpl-runanalysis-fast',
    name: 'RunAnalysis 快速模板',
    description: '低成本快速诊断，限制动作预算并关闭可选组件',
    components: buildWorkflowComponents('discover').map(item =>
      item.type === 'causal-memory' || item.type === 'critique-refiner'
        ? { ...item, enabled: false }
        : item,
    ),
    options: createBaseWorkflowOptions({
      enableCausalMemory: false,
      budget: { maxSteps: 4, maxRequests: 6, maxTotalTokens: 9000, maxParallelRequests: 1 },
      debugVerboseReport: false,
      causalMemoryTopK: 3,
      causalMemoryMaxChars: 900,
    }),
  },
]

export const MOCK_WORKFLOW: AgentWorkflowDefinition = {
  id: 'wf-main',
  name: 'RunAnalysis Compatible Workflow',
  description: '可平替 Unity RunAnalysis 的默认工作流模板',
  components: MOCK_WORKFLOW_TEMPLATES[0].components,
  options: MOCK_WORKFLOW_TEMPLATES[0].options,
  lastUpdated: BASE_TIME - 1000 * 60,
}

export const MOCK_CAUSAL_MEMORY_NODES: AgentCausalMemoryNode[] = [
  {
    id: 'm1',
    stepIndex: 1,
    phase: 'discover',
    actionType: 'get_project_manifest',
    nodeKind: 'tool-execution',
    success: true,
    summary: '成功读取项目清单，识别核心模块 12 个',
    why: '先建立代码边界，减少后续无效搜索',
    digest: 'manifest + module index',
    objectiveTags: ['manifest', 'code-boundary'],
    timestamp: BASE_TIME - 1000 * 60 * 10,
  },
  {
    id: 'm2',
    stepIndex: 2,
    phase: 'investigate',
    actionType: 'search_code',
    nodeKind: 'planner-decision',
    success: true,
    summary: '规划优先搜索 run_end 与 tower placement 相关片段',
    why: '与 RunSummary 的异常指标最相关',
    digest: 'query prioritization',
    objectiveTags: ['search', 'telemetry-correlation'],
    timestamp: BASE_TIME - 1000 * 60 * 8,
  },
  {
    id: 'm3',
    stepIndex: 3,
    phase: 'investigate',
    actionType: 'read_code_file',
    nodeKind: 'observation',
    success: true,
    summary: '读取核心结算逻辑后确认 score_delta 计算路径',
    why: '验证 telemetry 推断',
    digest: 'score delta path confirmed',
    objectiveTags: ['code-read', 'score-delta'],
    timestamp: BASE_TIME - 1000 * 60 * 6,
  },
]

export const MOCK_CAUSAL_MEMORY_EDGES: AgentCausalMemoryEdge[] = [
  {
    id: 'me1',
    fromNodeId: 'm1',
    toNodeId: 'm2',
    relationType: 'causes',
    note: '清单结果驱动搜索策略',
  },
  {
    id: 'me2',
    fromNodeId: 'm2',
    toNodeId: 'm3',
    relationType: 'refines',
    note: '搜索命中结果触发精读',
  },
]

export const MOCK_BRANCHES: Branch[] = [
  { name: 'main', headHash: 'a3f8c21', color: '#0070f3', isActive: true, isMerged: false },
  { name: 'feat/workflow-editor', headHash: 'd9e1b47', color: '#22c55e', isActive: false, isMerged: false },
  { name: 'fix/causal-memory', headHash: '7c2a9f0', color: '#f59e0b', isActive: false, isMerged: true },
]

export const MOCK_COMMITS: Commit[] = [
  {
    hash: 'a3f8c21',
    fullHash: 'a3f8c210394bde92a1f7cc2c4e9073b123456789',
    message: '工作流快照：启用 Causal Memory + Governance',
    timestamp: BASE_TIME - 1000 * 60 * 2,
    branch: 'main',
    parentHash: 'd9e1b47',
    parentHashes: ['d9e1b47'],
    tags: ['HEAD', 'latest', 'workflow'],
    author: 'agent',
    nodeIds: ['node-7', 'node-8', 'node-9'],
    workflowId: 'wf-main',
  },
  {
    hash: 'd9e1b47',
    fullHash: 'd9e1b470a9c3fa12b8e4d527c89abc0123456789',
    message: 'Merge feat/workflow-editor → main',
    timestamp: BASE_TIME - 1000 * 60 * 8,
    branch: 'main',
    parentHash: '5b1e3d9',
    parentHashes: ['5b1e3d9', '7c2a9f0'],
    tags: ['merge'],
    author: 'agent',
    nodeIds: [],
    workflowId: 'wf-main',
  },
  {
    hash: '7c2a9f0',
    fullHash: '7c2a9f0e1b234567890abcdef0123456789abcde',
    message: '修复 causal retrieval 排序偏差',
    timestamp: BASE_TIME - 1000 * 60 * 12,
    branch: 'fix/causal-memory',
    parentHash: '5b1e3d9',
    parentHashes: ['5b1e3d9'],
    tags: ['stable'],
    author: 'agent',
    nodeIds: ['node-5', 'node-6'],
    workflowId: 'wf-main',
  },
  {
    hash: '5b1e3d9',
    fullHash: '5b1e3d9f2a345678901bcdef01234567890abcde',
    message: '接入 ToolExecutor（search/read/telemetry）',
    timestamp: BASE_TIME - 1000 * 60 * 18,
    branch: 'main',
    parentHash: '2c4a7f1',
    parentHashes: ['2c4a7f1'],
    tags: [],
    author: 'agent',
    nodeIds: ['node-3', 'node-4'],
    workflowId: 'wf-main',
  },
  {
    hash: '2c4a7f1',
    fullHash: '2c4a7f1d3456789012cdef012345678901abcdef',
    message: '初始化 Orchestrator 可视化骨架',
    timestamp: BASE_TIME - 1000 * 60 * 25,
    branch: 'main',
    parentHash: null,
    parentHashes: [],
    tags: ['init'],
    author: 'user',
    nodeIds: ['node-1', 'node-2'],
    workflowId: 'wf-main',
  },
]

export const MOCK_NODES: AgentNode[] = [
  {
    id: 'node-1',
    kind: 'workflow-component',
    status: 'success',
    label: 'RunAnalysis Orchestrator',
    detail: 'baseline → planner/tool loop → synthesis',
    componentType: 'run-orchestrator',
    phase: 'discover',
    commitHash: '2c4a7f1',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 60 * 25,
  },
  {
    id: 'node-2',
    kind: 'workflow-component',
    status: 'success',
    label: 'Baseline Analyzer',
    detail: '从 RunSummary 提取首轮结论',
    componentType: 'baseline-analyzer',
    phase: 'discover',
    commitHash: '2c4a7f1',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 60 * 24,
    tokenCount: 312,
  },
  {
    id: 'node-3',
    kind: 'workflow-component',
    status: 'success',
    label: 'LLM Planner',
    detail: '规划下一动作：search_code',
    componentType: 'llm-planner',
    phase: 'investigate',
    commitHash: '5b1e3d9',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 60 * 18,
    duration: 85,
  },
  {
    id: 'node-4',
    kind: 'workflow-component',
    status: 'success',
    label: 'Tool Executor',
    detail: '执行 search_code + read_code_file',
    componentType: 'tool-executor',
    phase: 'investigate',
    commitHash: '5b1e3d9',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 60 * 17,
  },
  {
    id: 'node-5',
    kind: 'workflow-component',
    status: 'success',
    label: 'Causal Memory Graph',
    detail: '建立 m1->m2->m3 因果链',
    componentType: 'causal-memory',
    phase: 'investigate',
    commitHash: '7c2a9f0',
    branch: 'fix/causal-memory',
    timestamp: BASE_TIME - 1000 * 60 * 12,
    duration: 4200,
  },
  {
    id: 'node-6',
    kind: 'workflow-component',
    status: 'success',
    label: 'Deterministic Governance',
    detail: '去重动作签名，抑制低价值循环',
    componentType: 'governance-gate',
    phase: 'investigate',
    commitHash: '7c2a9f0',
    branch: 'fix/causal-memory',
    timestamp: BASE_TIME - 1000 * 60 * 11,
  },
  {
    id: 'node-7',
    kind: 'workflow-component',
    status: 'running',
    label: 'Summary Synthesizer',
    detail: '正在综合输出最终建议…',
    componentType: 'summary-synthesizer',
    phase: 'synthesize',
    commitHash: 'a3f8c21',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 60 * 2,
    tokenCount: 1847,
  },
  {
    id: 'node-8',
    kind: 'memory',
    status: 'running',
    label: 'memory.retrieve(causal_context)',
    tool: 'memory',
    commitHash: 'a3f8c21',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 30,
  },
  {
    id: 'node-9',
    kind: 'workflow-component',
    status: 'idle',
    label: 'Critique / Refinement',
    detail: '等待 summary 完成后执行',
    componentType: 'critique-refiner',
    phase: 'synthesize',
    commitHash: 'a3f8c21',
    branch: 'main',
    timestamp: BASE_TIME - 1000 * 20,
  },
]

export const MOCK_EDGES: AgentEdge[] = [
  { id: 'e1-2', source: 'node-1', target: 'node-2' },
  { id: 'e2-3', source: 'node-2', target: 'node-3' },
  { id: 'e3-4', source: 'node-3', target: 'node-4' },
  { id: 'e4-5', source: 'node-4', target: 'node-5', label: 'causal_enabled' },
  { id: 'e5-6', source: 'node-5', target: 'node-6' },
  { id: 'e6-7', source: 'node-6', target: 'node-7', label: 'synthesize' },
  { id: 'e7-8', source: 'node-7', target: 'node-8', animated: true },
  { id: 'e7-9', source: 'node-7', target: 'node-9' },
]

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    role: 'user',
    content: '请把 RunAnalysis 的 AI 组件做成可视化工作流，并支持版本管理。',
    timestamp: BASE_TIME - 1000 * 60 * 25,
    nodeId: 'node-1',
  },
  {
    id: 'msg-2',
    role: 'agent',
    content: '好的，我会先构建标准 RunAnalysis 工作流，再加入可配置组件和版本快照。',
    thinking: '先落地 orchestrator + planner + tool executor，再补 causal memory 和 governance。',
    timestamp: BASE_TIME - 1000 * 60 * 24,
    nodeId: 'node-2',
    status: 'success',
  },
  {
    id: 'msg-3',
    role: 'tool',
    content: '执行 search_code：定位 RunAnalysisAgentOrchestrator 相关调用链',
    timestamp: BASE_TIME - 1000 * 60 * 18,
    nodeId: 'node-4',
    toolName: 'filesystem',
    status: 'success',
    toolInput: { action: 'search_code', query: 'RunAnalysisAgentOrchestrator' },
    toolOutput: '命中：AgentModels.cs, LLMAgentPlanner.cs, AgentCausalMemory.cs, RunAnalysisAgentOrchestrator.cs',
  },
  {
    id: 'msg-4',
    role: 'tool',
    content: '执行 read_code_file：抽取 baseline/planner/tool-loop/synthesize 阶段机',
    timestamp: BASE_TIME - 1000 * 60 * 12,
    nodeId: 'node-5',
    toolName: 'shell',
    status: 'success',
    toolInput: { command: 'read_code_file RunAnalysisAgentOrchestrator.cs' },
    toolOutput: '识别流程：Baseline -> Planner Loop -> Governance -> Synthesize。',
  },
  {
    id: 'msg-5',
    role: 'agent',
    content: '正在将因果记忆节点注入工作流上下文，并生成版本快照...',
    thinking: '为每个 step 记录 causal 节点，构建检索 query（phase + expectedAction + queryText）。',
    timestamp: BASE_TIME - 1000 * 60 * 2,
    nodeId: 'node-7',
    status: 'running',
  },
]

export const MOCK_TOOL_EXECUTIONS: ToolExecution[] = [
  {
    id: 'exec-1',
    tool: 'filesystem',
    status: 'success',
    input: { action: 'search_code', query: 'RunAnalysisAgentOrchestrator' },
    output: 'AgentModels.cs\nLLMAgentPlanner.cs\nAgentCausalMemory.cs\nRunAnalysisAgentOrchestrator.cs',
    startTime: BASE_TIME - 1000 * 60 * 18,
    endTime: BASE_TIME - 1000 * 60 * 18 + 85,
    nodeId: 'node-4',
  },
  {
    id: 'exec-2',
    tool: 'shell',
    status: 'success',
    input: { command: 'read_code_file', path: 'RunAnalysisAgentOrchestrator.cs' },
    output: 'baseline -> planner/tool loop -> synthesis',
    startTime: BASE_TIME - 1000 * 60 * 12,
    endTime: BASE_TIME - 1000 * 60 * 12 + 4200,
    nodeId: 'node-5',
  },
  {
    id: 'exec-3',
    tool: 'memory',
    status: 'running',
    input: { action: 'retrieve', query: 'phase=synthesize expectedAction=finish' },
    startTime: BASE_TIME - 1000 * 30,
    nodeId: 'node-8',
  },
]
